### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 5) when calling nlp(string_ptr)

### ISSUE THREAD

**Issue by dzlab** [OpenMined/SyferText#5]
I cannot run tutorial 1 because of `ValueError: not enough values to unpack (expected 6, got 5)` when calling `nlp(string_ptr)`.
Here is stacktrace
```
>>> nlp(string_ptr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dzlab/Projects/ds/SyferText/syfertext/language.py", line 158, in __call__
    doc = self.make_doc(text)
  File "/Users/dzlab/Projects/ds/SyferText/syfertext/language.py", line 143, in make_doc
    self.tokenizer = self.tokenizer.send(text.location)
  File "/Users/dzlab/Projects/ds/SyferText/syfertext/tokenizer.py", line 230, in send
    ptr = self.owner.send(self, location)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/workers/base.py", line 395, in send
    self.send_obj(obj, worker)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/workers/base.py", line 607, in send_obj
    return self.send_msg(ObjectMessage(obj), location)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/workers/base.py", line 277, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/workers/virtual.py", line 7, in _send_msg
    return location._recv_msg(message)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/workers/virtual.py", line 10, in _recv_msg
    return self.recv_msg(message)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/workers/base.py", line 304, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/serde/serde.py", line 69, in deserialize
    return strategy(binary, worker)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/serde/msgpack/serde.py", line 369, in deserialize
    return _deserialize_msgpack_simple(simple_objects, worker)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/serde/msgpack/serde.py", line 360, in _deserialize_msgpack_simple
    return _detail(worker, simple_objects)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/serde/msgpack/serde.py", line 460, in _detail
    return detailers[obj[0]](worker, obj[1], **kwargs)
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/messaging/message.py", line 341, in detail
    return ObjectMessage(sy.serde.msgpack.serde._detail(worker, msg_tuple[0]))
  File "/usr/local/share/c3/conda/envs/env3.6/lib/python3.6/site-packages/syft-0.2.3a1-py3.6.egg/syft/serde/msgpack/serde.py", line 460, in _detail
    return detailers[obj[0]](worker, obj[1], **kwargs)
  File "/Users/dzlab/Projects/ds/SyferText/syfertext/pointers/doc_pointer.py", line 113, in detail
    simple_obj
ValueError: not enough values to unpack (expected 6, got 5)
```

**Comment by AlanAboudib** [comment]
Thank you @dzlab for signaling this issue. The problem was in the [\_\_init\_\_\.py](https://github.com/OpenMined/SyferText/blob/98abfc1e94f50e6329333e0acd4994e1e546b117/syfertext/__init__.py#L56-L64). Choosing the index to insert `tokenizer` and `DocPointer` detailers was buggy. you can see the new code [here](https://github.com/OpenMined/SyferText/blob/98abfc1e94f50e6329333e0acd4994e1e546b117/syfertext/__init__.py#L56-L64).
