### ISSUE TITLE
Installation Raises Error

### ISSUE THREAD

**Issue by RishabhBhatnagar** [OpenMined/SyferText#54]
Steps I've followed
### Without Environment
```
mkdir syfer_text; cd syfer_text
git init; git remote add _ https://github.com/OpenMinded/SyferText
git pull _ master
python3.8 setup.py install
```
### With Environment
```
virtualenv env; source env/bin/activate;
git clone https://www.github.com/OpenMinded/SyferText; cd SyferText
python3.8 setup.py install
```
I ran into the following error.
```
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'classifier'
  warnings.warn(msg)
running install
Checking .pth file support in /usr/local/lib/python3.8/dist-packages/
/usr/bin/python3.8 -E -c pass
TEST PASSED: /usr/local/lib/python3.8/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing syfertext.egg-info/PKG-INFO
writing dependency_links to syfertext.egg-info/dependency_links.txt
writing requirements to syfertext.egg-info/requires.txt
writing top-level names to syfertext.egg-info/top_level.txt
reading manifest file 'syfertext.egg-info/SOURCES.txt'
writing manifest file 'syfertext.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying syfertext.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying syfertext.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying syfertext.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying syfertext.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying syfertext.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setup(
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

This error remains the same on all python3.x versions. [Tried 3.5, 3.6, 3.8]

**Comment by AlanAboudib** [comment]
Thank you for signaling @RishabhBhatnagar. I am looking into this issue.

**Comment by AlanAboudib** [comment]
Problem should be solved now, can you confirm please @RishabhBhatnagar ?

**Comment by RishabhBhatnagar** [comment]
Yes, the issue is resolved.
