### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by arbazkhan971** [OpenMined/SyferText#55]
#### installation steps:
python3 -m pip install syfertext

#### Error occured:
Inside python3 interpreter

>>> import syfertext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/syfertext-0.1.0.dev1-py3.6.egg/syfertext/__init__.py", line 1, in <module>
    from .language import Language
  File "/usr/local/lib/python3.6/dist-packages/syfertext-0.1.0.dev1-py3.6.egg/syfertext/language.py", line 1, in <module>
    from .tokenizer import Tokenizer
  File "/usr/local/lib/python3.6/dist-packages/syfertext-0.1.0.dev1-py3.6.egg/syfertext/tokenizer.py", line 1, in <module>
    from .doc import Doc
  File "/usr/local/lib/python3.6/dist-packages/syfertext-0.1.0.dev1-py3.6.egg/syfertext/doc.py", line 1, in <module>
    from .token import Token
  File "/usr/local/lib/python3.6/dist-packages/syfertext-0.1.0.dev1-py3.6.egg/syfertext/token.py", line 1, in <module>
    from .utils import hash_string
  File "/usr/local/lib/python3.6/dist-packages/syfertext-0.1.0.dev1-py3.6.egg/syfertext/utils.py", line 1, in <module>
    import mmh3
ModuleNotFoundError: No module named 'mmh3'

**Comment by Syzygianinfern0** [comment]
Please use the  [Installation Instructions](https://github.com/OpenMined/SyferText#installation)
SyferText is not currently available as a pip install.

**Comment by arbazkhan971** [comment]
okay

**Comment by AlanAboudib** [comment]
Here is how to install SyferText 

```
python install setup.py
```
